"""empty message

Revision ID: 861f86c5923c
Revises: b20785afa63f
Create Date: 2022-02-09 08:57:32.365789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '861f86c5923c'
down_revision = 'b20785afa63f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('donations', sa.Column('item4', sa.String(length=100), nullable=True))
    op.add_column('donations', sa.Column('item5', sa.String(length=100), nullable=True))
    op.add_column('donations', sa.Column('item6', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('donations', 'item6')
    op.drop_column('donations', 'item5')
    op.drop_column('donations', 'item4')
    # ### end Alembic commands ###
