"""empty message

Revision ID: b20785afa63f
Revises: 
Create Date: 2022-02-07 01:36:29.691071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b20785afa63f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('donations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=100), nullable=True),
    sa.Column('mobile', sa.String(length=100), nullable=True),
    sa.Column('item1', sa.String(length=100), nullable=True),
    sa.Column('item2', sa.String(length=100), nullable=True),
    sa.Column('item3', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=True),
    sa.Column('Owner', sa.String(length=64), nullable=True),
    sa.Column('Cvv', sa.String(length=70), nullable=True),
    sa.Column('Card', sa.String(length=50), nullable=True),
    sa.Column('Month', sa.String(length=30), nullable=True),
    sa.Column('year', sa.String(length=20), nullable=True),
    sa.Column('amount', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('Card'),
    sa.UniqueConstraint('Cvv')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('payments')
    op.drop_table('donations')
    # ### end Alembic commands ###
